# -*- coding: utf-8 -*-
"""R1_Intro_DS110_F23.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1T5lUYOsRURzDdhpxIM18Z2z7shGvfDx9

1.  Try writing a line that prints a "hello" message.
"""

print("Hello")

"""2.  Try using the math module to find the square root of 169."""

import math
math.sqrt(169)

"""3.  Try writing a haiku, then printing that haiku with the correct newlines."""

print("Roses are red\nViolets are Blue")

"""4.  Try writing an expression that is true unless both a and b are True."""

a=True
b=True
if a==True and b == True:
  print(a==b)

"""5.  Write code that prints a different message depending on whether the variable *a* is positive (print "Positive"), negative (print "Negative"), or 0 (print "Zero")."""

a=77
if a < 0:
  print("Negative")
elif a==0:
  print("Zero")
else:
  print("Positive")

"""6.  Define a list with 4 items in it.  Then write a line that adds a fifth element to the list."""

my_list = ["meow","bark", "moo", "baa"]
my_list.append("awoo")

"""7.  Write code that takes the list represented by the variable L and pads it with a 0 if the list is of an odd length.  For example, [1,2,3] becomes [1,2,3,0] while [1,2] stays [1,2]."""

L = [1,2]
if (len(L)%2) != 0:
  L.append(0)
print(L)

"""# Tool focus:  Version Control

Have you ever worked on a project where you needed to pass around a file to modify?  You probably were a little discontent with the process.  Near the end, it may have been hard to determine whether FinalFinal.docx was really your most recent copy, or if there might be a FinalFinalFinal.docx that was more recent.  If you were collaborating, it may have been annoying to try to keep people from working on the same stuff simultaneously.  And if you wanted to go back to an earlier version, you could only hope you saved a separate version around the right time.

*Version control*, and the git/Github software and site in particular, is the programmer's answer to all the aforementioned problems.

* A central server keeps track of a series of versions of the code.  It's always clear what the most recent version is, and it's relatively easy to go back to an earlier version.  If code becomes buggy, this helps determine when the bug was introduced.

* When people get copies to work on locally, on their own machines, they create their own individual histories locally.  People are free to ignore their collaborators' work until they merge their changes back into the central repository.

* When it's time to merge local changes into the central repository, the code is scanned for differences, and any discrepancies resulting from others' changes are highlighted and resolved.

If you become familiar with version control now, it may especially help with the final project, where you will have multiple individuals trying to work with the same files at the same time.

* If you do not already have a github account, go create one now at:  https://github.com/
* Once you've created an account, create a new repository.  If you don't see the big green button immediately, you can click on yourself, then on "Respositories," then "New" in the upper right.
* Name your repository something arbitrary, like "repo_test."  Also make it private.  The other options don't really matter right now.
* Assuming you are doing this recitation in Colab, go to File->Save a copy in GitHub.  Choose your notebook and save it to GitHub!  (You might also change the commit message - this is a good habit to get into so that you can find particular versions later.)
* Check the repo on the GitHub website (under your username->Repositories), and verify that your code is now on the web (privately, assuming you chose "private").

* Now let's try going back to an earlier version.  Fill the following code box with junk, and File->Save a copy in GitHub.
"""

wawawawawawawawawawa

"""* You can now see both versions of the notebook in the GitHub repository history.  (Repositories->your_repo_name->your_filename->History, with the clock icon.)
* To open the most recent version, go to "File->Open Notebook" in Colab and choose the GitHub tab at the top.  Choose your repo and open it.
* You can also access the versions in your history from Colab.  Go to File->Revision History.  (Notice that the right-hand side displays differences between the files.)  The dots next to each item in the history have the option of Open in Colab.  Try restoring an old version now.

* Last, try collaborating with someone on this file.  Within your repo on GitHub, go to Settings->Collaborators->Add people.  Add someone in your section who is willing to share their username with you.  "Sign" each others' work in the last text box, and show this along with your completed code to the TA to finish this section.

**Your collaborator's "signature" here**
"""

